version: "3.8"

services:
  db:
    image: postgres:14.6
    restart: unless-stopped
    container_name: postgresql_backend_generated_app_8fdcd680_737d_4dec_b3b1_d9e327c1a85d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
#      - ./db:/var/lib/postgresql/data
      - ./create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      - spring.profiles.active=dev
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=password
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true